### ISSUE TITLE
--extract-conda-packages fails on Windows machines with > 60 processors

### ISSUE THREAD

**Issue by FaustinCarter** [conda-forge/conda-standalone-feedstock#12]
## Background
There is a bug in python on Windows that triggers when more than 60 concurrent processes are started.
https://bugs.python.org/issue26903 (patched, but didn't actually fix)
https://bugs.python.org/issue40263 (will actually fix, but not yet merged in)

## Issue
On  Windows machine with more than 60 processors (i.e. 4 chips, 4 cores, 4 logical cores = 64 processors) line 69 in the following code will cause a permanent hang.

https://github.com/conda-forge/conda-standalone-feedstock/blob/fb897ff9894b99d6934f68aa834e2c7d4668623a/recipe/entry_point.py#L58-L71

## Proposed fix
`ProcessPoolExecutor` defaults to setting `max_workers` equal to the number of processors on the machine. https://docs.python.org/3.2/library/concurrent.futures.html#processpoolexecutor

I see two obvious ways to fix this:
 1. Check for windows, and limit `max_workers` to 60 (with a note to remove when bpo-40263 is merged in)
 2. Add a CLI flag `--max-workers` and allow the user to pass in a custom value. Add a note in the documentation of conda constructor that this may be needed on Windows machines with lots of cores.

Option 1 will silently fix the problem, Option 2 adds some functionality and has the added benefit of allowing one to throttle down any custom python installer to not automatically hog all of the CPU cycles on what may be a shared machine.

**Comment by nehaljwani** [comment]
I remember this from https://twitter.com/ID_AA_Carmack/status/1248429550993719297

I thought this patch was supposed to fix it in python itself: https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0000-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch

@FaustinCarter Which version of conda-standalone are you using? It could be the case that conda-standalone hasn't been built since that patch was merged in conda-forge's feedstock.

**Comment by nehaljwani** [comment]
I've cut a new release - v4.9.2

Could you please check if the problem persists with it?

Regardless, I would be happy to accept a merge request for the CLI flag.

**Comment by FaustinCarter** [comment]
I built a new installer (via constructor) with conda-standalone 4.9.2. It still appears to be hanging forever. conda-standalone 4.7.5 works just fine.

With 4.9.2, running:
`_conda.exe constructor --prefix .\ --extract-conda-pkgs`, I eventually get a `ValueError: need at most 63 handles, got a sequence of length 65`. So it looks like the 64-1 fix somehow isn't propagating through to where it really needs to be.

I'm using python 3.7.8 from conda-forge, by the way.

**Comment by nehaljwani** [comment]
Hmm... for some reason, the new build for Windows again picked up python-v3.7.1 , that's weird. Let me dig

**Comment by nehaljwani** [comment]
Opened https://github.com/conda-forge/python-feedstock/pull/405

**Comment by FaustinCarter** [comment]
Does conda-standalone need to be re-released after the patch to py37?

**Comment by nehaljwani** [comment]
@FaustinCarter I've cut another release. Could you try out:
https://conda.anaconda.org/conda-forge/win-64/conda-standalone-4.9.2-h57928b3_2.tar.bz2

**Comment by FaustinCarter** [comment]
This release is working; thanks so much for helping get that patch backported!
