### ISSUE TITLE
Fix osx codesigning for pyinstaller > 4.3

### ISSUE THREAD

**Issue by FaustinCarter** [conda-forge/conda-standalone-feedstock#51]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Since roughly pyinstaller 4.3, codesigning is broken on OSX. It's not clear at all to me what the right path is to fix this, but there is a thread here that might provide some light on the subject to an expert: https://github.com/pyinstaller/pyinstaller/issues/6167 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jaimergp** [comment]
I think it has to do with a non-Apple `codesign` being present in the same environment as `conda` (`base`). Basically we need to shadow that with `/usr/bin/codesign` (or have PyInstaller use the abs path).

This is what we discussed for [this block](https://github.com/conda-forge/conda-standalone-feedstock/pull/49/files#diff-d7075654874cb08007a21aaab3ecd4b3453a9087e7505d034d548b8938b599bcR9-R14), so I think we can close.
